# Generated by Django 3.2.12 on 2022-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ussdpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('service_code', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('codeinput', models.CharField(max_length=50)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('session_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
