# Generated by Django 4.0.3 on 2022-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_alter_ussdpayment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdpayment',
            name='QuestionVotingFOr',
            field=models.IntegerField(default=0),
        ),
    ]
