# Generated by Django 4.0.3 on 2022-04-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_ussdpayment_questionvotingfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
