# Generated by Django 4.0.3 on 2022-04-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_ussdpayment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdpayment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
