# Generated by Django 4.0.3 on 2022-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_alter_ussdpayment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdpayment',
            name='nw_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
