# Generated by Django 4.0.3 on 2022-04-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0006_ussdpayment_nw_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdpayment',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
