# Generated by Django 4.0.3 on 2022-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0007_ussdpayment_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSuccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ussdpayment',
            name='session_complete',
        ),
    ]
