# Generated by Django 3.2.12 on 2022-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='code',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
