# Generated by Django 3.2.12 on 2022-03-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='webPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('question_id', models.IntegerField(default=0)),
                ('choice', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
